In [1]:
import pandas as pd
import numpy as np
import scipy as sp

In [6]:
df_properties2016 = pd.read_csv("/home/mishraka/repos/Data_Science/Zillow_data/properties_2016.csv")

/home/mishraka/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (22,32,34,49,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
df_properties2016.head()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2015.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,650756.0,1413387.0,2015.0,762631.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,7.0,NaN,NaN,...,1.0,NaN,571346.0,1156834.0,2015.0,585488.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,NaN,NaN,193796.0,433491.0,2015.0,239695.0,5725.17,NaN,NaN,NaN

In [8]:
df_properties2016.isna().sum()

parcelid                              0
airconditioningtypeid           2173698
architecturalstyletypeid        2979156
basementsqft                    2983589
bathroomcnt                       11462
bedroomcnt                        11450
buildingclasstypeid             2972588
buildingqualitytypeid           1046729
calculatedbathnbr                128912
decktypeid                      2968121
finishedfloor1squarefeet        2782500
calculatedfinishedsquarefeet      55565
finishedsquarefeet12             276033
finishedsquarefeet13            2977545
finishedsquarefeet15            2794419
finishedsquarefeet50            2782500
finishedsquarefeet6             2963216
fips                              11437
fireplacecnt                    2672580
fullbathcnt                      128912
garagecarcnt                    2101950
garagetotalsqft                 2101950
hashottuborspa                  2916203
heatingorsystemtypeid           1178816
latitude                          11437
longitude                         11437
lotsizesquarefeet                276099
poolcnt                         2467683
poolsizesum                     2957257
pooltypeid10                    2948278
pooltypeid2                     2953142
pooltypeid7                     2499758
propertycountylandusecode         12277
propertylandusetypeid             11437
propertyzoningdesc              1006588
rawcensustractandblock            11437
regionidcity                      62845
regionidcounty                    11437
regionidneighborhood            1828815
regionidzip                       13980
roomcnt                           11475
storytypeid                     2983593
threequarterbathnbr             2673586
typeconstructiontypeid          2978470
unitcnt                         1007727
yardbuildingsqft17              2904862
yardbuildingsqft26              2982570
yearbuilt                         59928
numberofstories                 2303148
fireplaceflag                   2980054
structuretaxvaluedollarcnt        54982
taxvaluedollarcnt                 42550
assessmentyear                    11439
landtaxvaluedollarcnt             67733
taxamount                         31250
taxdelinquencyflag              2928755
taxdelinquencyyear              2928753
censustractandblock               75126
dtype: int64

In [9]:
df_properties2016.shape

(2985217, 58)

In [10]:
df_properties2017 = pd.read_csv("/home/mishraka/repos/Data_Science/Zillow_data/properties_2017.csv")

/home/mishraka/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)